name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: Release
    steps:
    - name: Restore dependencies
      run: dotnet restore ./ConsoleApp/ConsoleApp.csproj
    - name: Build
      run: dotnet build ./ConsoleApp/ConsoleApp.csproj --no-restore --configuration ${{ env.buildConfiguration }}
